2023-06-19 12:06:44,114 INFO    MainThread:14885 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-19 12:06:44,114 INFO    MainThread:14885 [wandb_setup.py:_flush():76] Configure stats pid to 14885
2023-06-19 12:06:44,114 INFO    MainThread:14885 [wandb_setup.py:_flush():76] Loading settings from /home/andrea/.config/wandb/settings
2023-06-19 12:06:44,114 INFO    MainThread:14885 [wandb_setup.py:_flush():76] Loading settings from /home/andrea/Documenti/Computer Science/Natural Language Procesing/nlp2023-hw2/wandb/settings
2023-06-19 12:06:44,114 INFO    MainThread:14885 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-19 12:06:44,114 INFO    MainThread:14885 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-06-19 12:06:44,114 WARNING MainThread:14885 [wandb_setup.py:_flush():76] Could not save program above cwd: /home/andrea/Documents/Computer Science/Natural Language Procesing/nlp2023-hw2/train_model.py
2023-06-19 12:06:44,114 INFO    MainThread:14885 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '/home/andrea/Documents/Computer Science/Natural Language Procesing/nlp2023-hw2/train_model.py'}
2023-06-19 12:06:44,114 INFO    MainThread:14885 [wandb_init.py:_log_setup():507] Logging user logs to ./wandb/run-20230619_120644-uvt4x3qc/logs/debug.log
2023-06-19 12:06:44,114 INFO    MainThread:14885 [wandb_init.py:_log_setup():508] Logging internal logs to ./wandb/run-20230619_120644-uvt4x3qc/logs/debug-internal.log
2023-06-19 12:06:44,114 INFO    MainThread:14885 [wandb_init.py:init():547] calling init triggers
2023-06-19 12:06:44,115 INFO    MainThread:14885 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-06-19 12:06:44,115 INFO    MainThread:14885 [wandb_init.py:init():596] starting backend
2023-06-19 12:06:44,115 INFO    MainThread:14885 [wandb_init.py:init():600] setting up manager
2023-06-19 12:06:44,120 INFO    MainThread:14885 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-06-19 12:06:44,125 INFO    MainThread:14885 [wandb_init.py:init():606] backend started and connected
2023-06-19 12:06:44,133 INFO    MainThread:14885 [wandb_init.py:init():703] updated telemetry
2023-06-19 12:06:44,158 INFO    MainThread:14885 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-06-19 12:06:44,701 ERROR   MainThread:14885 [wandb_init.py:init():762] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-06-19 12:06:44,821 ERROR   MainThread:14885 [wandb_init.py:init():1170] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 768, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
